channels:
  - conda-forge
dependencies:
  - donfig
  - gdal
  - netifaces
  - pip
  - pip:
    - posttroll==1.12.1
  - python=3.12
  - pyyaml
  - pyzmq
  - requests>=2.32.0
  - urllib3>=2.2.2
  - zeromq
