channels:
  - conda-forge
dependencies:
  - donfig
  - gdal
  - git
  - netifaces
  - pip
  - pip:
    - posttroll==1.10.0
  - python=3.11
  - pyyaml
  - pyzmq
  - requests>=2.32.0
  - urllib3
  - zeromq
